// Parte A — "Programá al robot" (20 ítems). Ver docs/02-banco-de-items.md.
import {
  c,
  call,
  e,
  HOLE,
  ifHole,
  ifPath,
  ifRock,
  optCond,
  optFix,
  optPiece,
  optProg,
  path,
  prog,
  rep,
  rock,
  seq,
  until,
  whileP,
  type ItemA,
} from "./model";

// Consignas cortas y con la misma forma para cada tipo de misión. La etiqueta de la misión
// ("Completar", "Arreglar", "Comparar") remite a la práctica de ese formato (ver tutorial.ts).
const PROMPT_MAZE = "¿Qué programa lleva al robot hasta la base?";
const PROMPT_CANVAS = "¿Qué programa dibuja esta figura?";
const HOLE_MAZE = "Al programa le falta una pieza. ¿Cuál va en el hueco para llegar a la base?";
const HOLE_CANVAS = "Al programa le falta una pieza. ¿Cuál va en el hueco para dibujar la figura?";
const HOLE_COND = "Al programa le falta una condición. ¿Cuál va en el hueco para llegar a la base?";
// En arreglar, la pregunta ("elegí el cambio que lo arregla") va en los pasos que se muestran al lado.
const FIX_MAZE = "El robot se choca: el programa tiene un error.";
const FIX_CANVAS = "Dibuja otra figura: el programa tiene un error.";

export const ITEMS_A: ItemA[] = [
  // ───────────────────────── A1 · Secuencias ─────────────────────────
  {
    id: "A1.1",
    part: "A",
    block: "A1",
    concept: "secuencias",
    task: "S",
    prompt: PROMPT_MAZE,
    map: {
      kind: "maze",
      cols: 4,
      rows: 4,
      start: c(1, 1),
      base: c(4, 3),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(3, 1), c(4, 1)),
        e(c(2, 1), c(2, 2)), e(c(4, 1), c(4, 2)),
        e(c(1, 2), c(2, 2)), e(c(2, 2), c(3, 2)),
        e(c(1, 2), c(1, 3)), e(c(3, 2), c(3, 3)), e(c(4, 2), c(4, 3)),
        e(c(1, 3), c(2, 3)), e(c(3, 3), c(4, 3)),
        e(c(2, 3), c(2, 4)), e(c(3, 3), c(3, 4)),
        e(c(1, 4), c(2, 4)), e(c(2, 4), c(3, 4)), e(c(3, 4), c(4, 4)),
      ],
    },
    options: [optProg(seq("→↓→↓→")), optProg(seq("→→↓↓→")), optProg(seq("↓→↓→→")), optProg(seq("→↓→↓↓"))],
    correct: 0,
    notes: "Ancla fácil. Distractores: mismas flechas en otro orden (chocan) y paso final equivocado.",
  },
  {
    id: "A1.2",
    part: "A",
    block: "A1",
    concept: "secuencias",
    task: "S",
    prompt: PROMPT_CANVAS,
    map: { kind: "canvas", cols: 4, rows: 3, start: c(1, 1), target: prog(seq("→→↓←↓→")) },
    options: [optProg(seq("→→↓←↓→")), optProg(seq("→→↓→↓←")), optProg(seq("→↓←↓→")), optProg(seq("→→↓←↓←"))],
    correct: 0,
    notes: "Distractores: figura espejada, primer tramo corto, último tramo al revés.",
  },

  // ───────────────────────── A2 · Repetir N veces ─────────────────────────
  {
    id: "A2.1",
    part: "A",
    block: "A2",
    concept: "repetir",
    task: "S",
    prompt: PROMPT_MAZE,
    map: {
      kind: "maze",
      cols: 6,
      rows: 3,
      start: c(1, 1),
      base: c(6, 3),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(3, 1)), e(c(3, 1), c(4, 1)),
        e(c(4, 1), c(4, 2)), e(c(4, 2), c(4, 3)),
        e(c(4, 3), c(5, 3)), e(c(5, 3), c(6, 3)),
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(1, 3)), e(c(1, 3), c(2, 3)),
      ],
    },
    options: [
      optProg([rep(3, seq("→")), rep(2, seq("↓")), rep(2, seq("→"))]),
      optProg([rep(2, seq("→")), rep(2, seq("↓")), rep(3, seq("→"))]),
      optProg([rep(3, seq("→")), rep(3, seq("↓")), rep(2, seq("→"))]),
      optProg([rep(3, seq("→")), rep(2, seq("↓")), rep(3, seq("→"))]),
    ],
    correct: 0,
    notes: "Distractores: contar mal en cada bucle (choca, se cae del mapa, se pasa de largo).",
  },
  {
    id: "A2.2",
    part: "A",
    block: "A2",
    concept: "repetir",
    task: "C",
    prompt: HOLE_CANVAS,
    map: {
      kind: "canvas",
      cols: 5,
      rows: 6,
      start: c(1, 3),
      target: prog([rep(4, seq("→")), rep(2, seq("↓")), rep(4, seq("←"))]),
    },
    given: prog([rep(4, seq("→")), HOLE, rep(4, seq("←"))]),
    options: [optPiece([rep(2, seq("↓"))]), optPiece([rep(3, seq("↓"))]), optPiece([rep(2, seq("↑"))]), optPiece(seq("↓"))],
    correct: 0,
    notes: "Hay que contar el lado vertical (2) y elegir la dirección.",
  },
  {
    id: "A2.3",
    part: "A",
    block: "A2",
    concept: "repetir",
    task: "D",
    prompt: FIX_MAZE,
    map: {
      kind: "maze",
      cols: 5,
      rows: 3,
      start: c(1, 1),
      base: c(5, 3),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(3, 1)), e(c(3, 1), c(4, 1)), e(c(4, 1), c(5, 1)),
        e(c(3, 1), c(3, 2)), e(c(3, 2), c(3, 3)),
        e(c(3, 3), c(4, 3)), e(c(4, 3), c(5, 3)),
        e(c(5, 1), c(5, 2)),
      ],
    },
    given: prog([rep(3, seq("→")), rep(2, seq("↓")), rep(2, seq("→"))]),
    options: [
      optFix([rep(2, seq("→")), rep(2, seq("↓")), rep(2, seq("→"))], [rep(3, seq("→"))], [rep(2, seq("→"))]),
      optFix([rep(3, seq("→")), rep(3, seq("↓")), rep(2, seq("→"))], [rep(2, seq("↓"))], [rep(3, seq("↓"))]),
      optFix([rep(4, seq("→")), rep(2, seq("↓")), rep(2, seq("→"))], [rep(3, seq("→"))], [rep(4, seq("→"))]),
      optFix([rep(3, seq("→")), rep(2, seq("↓")), ...seq("→")], [rep(2, seq("→"))], seq("→")),
    ],
    correct: 0,
    notes: "El robot queda en (4,1) y abajo no hay puente: el error está en el primer bucle. El distractor 'repetir 4' tienta por el puente (5,1)-(5,2), que no sigue.",
  },

  // ───────────────────────── A3 · Repetir hasta / mientras ─────────────────────────
  {
    id: "A3.1",
    part: "A",
    block: "A3",
    concept: "hasta",
    task: "S",
    prompt: PROMPT_MAZE,
    map: {
      kind: "maze",
      cols: 4,
      rows: 4,
      start: c(1, 1),
      base: c(4, 4),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(2, 2)), e(c(2, 2), c(3, 2)),
        e(c(3, 2), c(3, 3)), e(c(3, 3), c(4, 3)), e(c(4, 3), c(4, 4)),
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(2, 2)), e(c(3, 1), c(4, 1)),
      ],
    },
    options: [
      optProg([until(seq("→↓"))]),
      optProg([until(seq("↓→"))]),
      optProg([rep(2, seq("→↓"))]),
      optProg([until(seq("→→↓"))]),
    ],
    correct: 0,
    notes: "Escalera de 3 escalones; el bucle contado se queda corto.",
  },
  {
    id: "A3.2",
    part: "A",
    block: "A3",
    concept: "hasta",
    task: "C",
    prompt: HOLE_MAZE,
    map: {
      kind: "maze",
      cols: 5,
      rows: 4,
      start: c(1, 1),
      base: c(4, 3),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(3, 1)), e(c(3, 1), c(4, 1)),
        e(c(4, 1), c(4, 2)), e(c(4, 2), c(4, 3)), e(c(4, 3), c(4, 4)),
      ],
    },
    given: prog([whileP("R", seq("→")), HOLE]),
    options: [optPiece([rep(2, seq("↓"))]), optPiece([whileP("D", seq("↓"))]), optPiece(seq("↓")), optPiece([rep(3, seq("↓"))])],
    correct: 0,
    notes: "El camino sigue una casilla más abajo de la base a propósito: 'mientras haya camino ↓' se pasa de largo.",
  },
  {
    id: "A3.3",
    part: "A",
    block: "A3",
    concept: "hasta",
    task: "D",
    prompt: FIX_MAZE,
    map: {
      kind: "maze",
      cols: 5,
      rows: 3,
      start: c(1, 1),
      base: c(5, 3),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(3, 1)), e(c(3, 1), c(3, 2)),
        e(c(3, 2), c(4, 2)), e(c(4, 2), c(5, 2)), e(c(5, 2), c(5, 3)),
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(2, 2)),
      ],
    },
    given: prog([until(seq("→↓"))]),
    options: [
      optFix([until(seq("→→↓"))], seq("→↓"), seq("→→↓")),
      optFix([until(seq("→↑"))], seq("↓"), seq("↑")),
      optFix([rep(2, seq("→↓"))], [until([])], [rep(2, [])]),
      optFix([until(seq("↓→"))], seq("→↓"), seq("↓→")),
    ],
    correct: 0,
    notes: "Los escalones son de dos casillas: falta un → dentro del bucle.",
  },

  // ───────────────────────── A4 · Bucles anidados ─────────────────────────
  {
    id: "A4.1",
    part: "A",
    block: "A4",
    concept: "anidados",
    task: "S",
    prompt: PROMPT_CANVAS,
    map: { kind: "canvas", cols: 7, rows: 4, start: c(1, 4), target: prog([rep(3, [rep(2, seq("→")), ...seq("↑")])]) },
    options: [
      optProg([rep(3, [rep(2, seq("→")), ...seq("↑")])]),
      optProg([rep(2, [rep(3, seq("→")), ...seq("↑")])]),
      optProg([rep(3, seq("→↑"))]),
      optProg([rep(6, seq("→")), rep(3, seq("↑"))]),
    ],
    correct: 0,
    notes: "Escalera de 3 escalones de 2. Distractores: bucles intercambiados, sin anidar, secuencial.",
  },
  {
    id: "A4.2",
    part: "A",
    block: "A4",
    concept: "anidados",
    task: "C",
    prompt: HOLE_MAZE,
    map: {
      kind: "maze",
      cols: 5,
      rows: 3,
      start: c(1, 1),
      base: c(5, 1),
      paths: [
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(1, 3)),
        e(c(2, 1), c(2, 2)), e(c(2, 2), c(2, 3)),
        e(c(3, 1), c(3, 2)), e(c(3, 2), c(3, 3)),
        e(c(4, 1), c(4, 2)), e(c(4, 2), c(4, 3)),
        e(c(1, 3), c(2, 3)), e(c(2, 1), c(3, 1)), e(c(3, 3), c(4, 3)), e(c(4, 1), c(5, 1)),
        e(c(5, 1), c(5, 2)), e(c(5, 2), c(5, 3)),
      ],
    },
    given: prog([rep(2, [HOLE, ...seq("→"), rep(2, seq("↑")), ...seq("→")])]),
    options: [optPiece([rep(2, seq("↓"))]), optPiece([rep(2, seq("↑"))]), optPiece(seq("↓")), optPiece([rep(3, seq("↓"))])],
    correct: 0,
    notes: "Laberinto peine: bajar 2, derecha, subir 2, derecha; dos veces.",
  },
  {
    id: "A4.3",
    part: "A",
    block: "A4",
    concept: "anidados",
    task: "D",
    prompt: FIX_CANVAS,
    map: { kind: "canvas", cols: 7, rows: 7, start: c(1, 7), target: prog([rep(3, [...seq("→"), rep(2, seq("↑"))])]) },
    given: prog([rep(3, [rep(2, seq("→")), ...seq("↑")])]),
    options: [
      optFix([rep(3, [...seq("→"), rep(2, seq("↑"))])], [rep(2, seq("→")), ...seq("↑")], [...seq("→"), rep(2, seq("↑"))]),
      optFix([rep(2, [rep(2, seq("→")), ...seq("↑")])], [rep(3, [])], [rep(2, [])]),
      optFix([rep(3, seq("→↑"))], [rep(2, seq("→"))], seq("→")),
      optFix([rep(3, [rep(2, seq("→")), rep(2, seq("↑"))])], seq("↑"), [rep(2, seq("↑"))]),
    ],
    correct: 0,
    notes: "Los escalones son 1 a la derecha y 2 arriba: el bucle interno tiene que ser el de ↑.",
  },

  // ───────────────────────── A5 · Si (condicional simple) ─────────────────────────
  {
    id: "A5.1",
    part: "A",
    block: "A5",
    concept: "si",
    task: "S",
    prompt: PROMPT_MAZE,
    map: { kind: "maze", cols: 6, rows: 3, start: c(1, 1), base: c(6, 3), allPaths: true, rocks: [c(2, 1), c(4, 2)] },
    options: [
      optProg([until([ifRock("R", seq("↓")), ...seq("→")])]),
      optProg([until([...seq("→"), ifRock("R", seq("↓"))])]),
      optProg([until([ifRock("R", seq("↑")), ...seq("→")])]),
      optProg([until(seq("↓→"))]),
    ],
    correct: 0,
    notes: "Distractores: chequear después de moverse (choca), desvío hacia arriba (se cae), sin condicional.",
  },
  {
    id: "A5.2",
    part: "A",
    block: "A5",
    concept: "si",
    task: "C",
    prompt: HOLE_COND,
    map: {
      kind: "maze",
      cols: 6,
      rows: 3,
      start: c(1, 1),
      base: c(6, 3),
      allPaths: true,
      walls: [e(c(1, 2), c(2, 2))],
      rocks: [c(3, 1), c(5, 2)],
    },
    given: prog([until([ifHole(seq("↓")), ...seq("→")])]),
    options: [optCond(rock("R")), optCond(path("D")), optCond(rock("D")), optCond(rock("L"))],
    correct: 0,
    notes: "'hay camino ↓' baja en la primera casilla y choca con la pared; las otras chocan con la roca.",
  },
  {
    id: "A5.3",
    part: "A",
    block: "A5",
    concept: "si",
    task: "D",
    prompt: FIX_MAZE,
    map: { kind: "maze", cols: 6, rows: 3, start: c(1, 2), base: c(6, 3), allPaths: true, rocks: [c(3, 2), c(5, 1)] },
    given: prog([until([ifRock("R", seq("↑")), ...seq("→")])]),
    options: [
      optFix([until([ifRock("R", seq("↓")), ...seq("→")])], seq("↑"), seq("↓")),
      optFix([until([ifRock("U", seq("↑")), ...seq("→")])], [ifRock("R", [])], [ifRock("U", [])]),
      optFix([until([ifPath("R", seq("↑")), ...seq("→")])], [ifRock("R", [])], [ifPath("R", [])]),
      optFix([until([ifRock("R", seq("↓↓")), ...seq("→")])], seq("↑"), seq("↓↓")),
    ],
    correct: 0,
    notes: "Esquivar por arriba lleva al robot a la fila 1, donde otra roca lo hace salir del mapa. Distractores: cambiar la condición (roca ↑, camino →) o bajar de más.",
  },

  // ───────────────────────── A6 · Si-sino ─────────────────────────
  {
    id: "A6.1",
    part: "A",
    block: "A6",
    concept: "si-sino",
    task: "S",
    prompt: PROMPT_MAZE,
    map: {
      kind: "maze",
      cols: 5,
      rows: 4,
      start: c(1, 1),
      base: c(5, 4),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(3, 1)), e(c(3, 1), c(3, 2)),
        e(c(3, 2), c(4, 2)), e(c(4, 2), c(4, 3)), e(c(4, 3), c(5, 3)), e(c(5, 3), c(5, 4)),
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(1, 3)),
      ],
    },
    options: [
      optProg([until([ifPath("R", seq("→"), seq("↓"))])]),
      optProg([until([ifPath("R", seq("→"), seq("↑"))])]),
      optProg([until([ifPath("D", seq("↓"), seq("→"))])]),
      optProg([until(seq("→↓"))]),
    ],
    correct: 0,
    notes: "Avanzar mientras se pueda; si no, bajar. La columna 1 es un callejón sin salida.",
  },
  {
    id: "A6.2",
    part: "A",
    block: "A6",
    concept: "si-sino",
    task: "C",
    prompt: HOLE_COND,
    map: { kind: "maze", cols: 6, rows: 3, start: c(1, 1), base: c(6, 3), allPaths: true, rocks: [c(3, 1), c(5, 2), c(2, 3)] },
    given: prog([until([ifHole(seq("↓"), seq("→"))])]),
    options: [optCond(rock("R")), optCond(rock("D")), optCond(path("D")), optCond(path("R"))],
    correct: 0,
    notes: "La roca de (2,3) hace fallar las condiciones sobre 'camino'.",
  },
  {
    id: "A6.3",
    part: "A",
    block: "A6",
    concept: "si-sino",
    task: "D",
    prompt: FIX_MAZE,
    map: {
      kind: "maze",
      cols: 5,
      rows: 4,
      start: c(1, 1),
      base: c(5, 4),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(3, 1)), e(c(3, 1), c(3, 2)),
        e(c(3, 2), c(4, 2)), e(c(4, 2), c(4, 3)), e(c(4, 3), c(5, 3)), e(c(5, 3), c(5, 4)),
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(1, 3)),
      ],
    },
    given: prog([until([ifPath("D", seq("→"), seq("↓"))])]),
    options: [
      optFix([until([ifPath("R", seq("→"), seq("↓"))])], [ifPath("D", [])], [ifPath("R", [])]),
      optFix([until([ifRock("D", seq("→"), seq("↓"))])], [ifPath("D", [])], [ifRock("D", [])]),
      optFix([until([ifPath("D", seq("↓"), seq("↓"))])], seq("→"), seq("↓")),
      optFix([until([ifPath("D", seq("→"), seq("→"))])], seq("↓"), seq("→")),
    ],
    correct: 0,
    notes: "La condición mira para el lado equivocado: en (1,1) hay camino ↓ (callejón) y avanza →; en (2,1) no hay camino ↓, entonces baja por el si no y se choca. Hay que seguir el si / si no dos veces.",
  },

  // ───────────────────────── A7 · Funciones simples ─────────────────────────
  {
    id: "A7.1",
    part: "A",
    block: "A7",
    concept: "funciones",
    task: "C",
    prompt: "A Paso le falta lo de adentro. ¿Cuál va en el hueco para dibujar la figura?",
    map: {
      kind: "canvas",
      cols: 9,
      rows: 5,
      start: c(1, 5),
      target: prog([rep(3, [call("Paso")]), ...seq("→→")], [{ name: "Paso", body: seq("→↑") }]),
    },
    given: prog([rep(3, [call("Paso")]), ...seq("→→")], [{ name: "Paso", body: [HOLE] }]),
    options: [optPiece(seq("→↑")), optPiece(seq("↑→")), optPiece(seq("→→↑")), optPiece(seq("↑→→"))],
    correct: 0,
    notes: "Escalera de 3 escalones de 1 y una línea final de 2.",
  },
  {
    id: "A7.2",
    part: "A",
    block: "A7",
    concept: "funciones",
    task: "C",
    prompt: HOLE_MAZE,
    map: {
      kind: "maze",
      cols: 5,
      rows: 4,
      start: c(1, 1),
      base: c(4, 4),
      paths: [
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(2, 2)), e(c(2, 2), c(3, 2)), e(c(3, 2), c(3, 3)),
        e(c(3, 3), c(3, 4)), e(c(3, 4), c(4, 4)),
        e(c(3, 2), c(4, 2)), e(c(4, 2), c(4, 3)), e(c(4, 3), c(5, 3)),
      ],
    },
    given: prog([call("Bajar"), HOLE, call("Bajar")], [{ name: "Bajar", body: seq("↓→") }]),
    options: [optPiece(seq("→↓")), optPiece(seq("↓→")), optPiece([call("Bajar")]), optPiece(seq("→→"))],
    correct: 0,
    notes: "Hay que ejecutar mentalmente la función dos veces y leer la pared entre (2,2) y (2,3).",
  },
  {
    id: "A7.3",
    part: "A",
    block: "A7",
    concept: "funciones",
    task: "E",
    prompt: "¿Qué programa dibuja lo mismo, sin usar Cuadro?",
    map: {
      kind: "canvas",
      cols: 5,
      rows: 3,
      start: c(1, 1),
      target: prog([rep(2, [call("Cuadro"), ...seq("→")])], [{ name: "Cuadro", body: seq("→↓←↑") }]),
    },
    given: prog([rep(2, [call("Cuadro"), ...seq("→")])], [{ name: "Cuadro", body: seq("→↓←↑") }]),
    options: [
      optProg([rep(2, seq("→↓←↑→"))]),
      optProg(seq("→↓←↑→↓←↑")),
      optProg(seq("→↓←↑→→→↓←↑")),
      optProg(seq("→→↓←←↑")),
    ],
    correct: 0,
    notes: "El más difícil de la Parte A: hay que desenrollar función y bucle. Dos cuadrados pegados.",
  },
];
