// Parte B — "Desafíos de lógica" (8 ítems, sin código). Ver docs/02-banco-de-items.md.
// Cada ítem separa los datos (frases cortas, en lista) de la pregunta, para bajar la carga de lectura.
// En B2, B4, B6 y B8 las opciones se dibujan (optionFigure); el texto de `options` queda para
// exportar y para la revisión.
import type { ItemB } from "./model";

export const ITEMS_B: ItemB[] = [
  {
    id: "B1",
    part: "B",
    practice: "descomposicion",
    facts: [
      "Para pintar una pared hay tres tareas: mover los muebles (10 minutos), tapar el piso (5 minutos) y pintar (30 minutos).",
      "Dos robots trabajan al mismo tiempo. Cada tarea la hace un solo robot.",
      "Pintar se puede empezar recién cuando las otras dos tareas terminaron.",
    ],
    prompt: "¿Cuánto tardan, como mínimo, en terminar todo?",
    figure: "pared",
    options: ["40 minutos", "45 minutos", "35 minutos", "30 minutos"],
    correct: 0,
    notes: "Las dos primeras tareas van en paralelo (10), después pintar (30). 45 es todo en serie.",
  },
  {
    id: "B2",
    part: "B",
    practice: "patrones",
    facts: ["El collar empieza en el nudo y sigue un patrón que se repite."],
    prompt: "¿Qué instrucción arma este collar?",
    figure: "collar",
    optionFigure: "collar",
    options: ["repetir { ● ● ▲ }", "repetir { ● ▲ ● }", "repetir { ● ▲ }", "repetir { ● ● ▲ ▲ }"],
    correct: 0,
    notes: "Reconocer el período del patrón desde el nudo.",
  },
  {
    id: "B3",
    part: "B",
    practice: "patrones",
    facts: [
      "Para acortar un mensaje se cuenta cuántas letras iguales hay seguidas y se escribe el número y la letra.",
      "Ejemplo: AAABBBBCC se escribe 3A4B2C.",
    ],
    prompt: "¿Cómo se escribe RRRRRVVVAA?",
    figure: "compresion",
    options: ["5R3V2A", "4R3V2A", "5R2V3A", "R5V3A2"],
    correct: 0,
    notes: "Generalizar una regla de codificación a partir de un ejemplo.",
  },
  {
    id: "B4",
    part: "B",
    practice: "representacion",
    facts: [
      "Cada tarjeta vale los puntos que tiene: 8, 4, 2 y 1.",
      "Para formar un número se eligen tarjetas y se suman sus puntos. Cada tarjeta se usa una sola vez.",
    ],
    prompt: "¿Qué tarjetas forman el 11?",
    figure: "tarjetas",
    optionFigure: "tarjetas",
    options: ["8, 2 y 1", "8 y 4", "4, 2 y 1", "8, 4 y 1"],
    correct: 0,
    notes: "Representación binaria sin nombrarla.",
  },
  {
    id: "B5",
    part: "B",
    practice: "abstraccion",
    facts: ["El mapa muestra los caminos del barrio.", "El número de cada camino es la cantidad de cuadras."],
    prompt: "¿Cuál es el camino más corto de la escuela a la plaza?",
    figure: "mapa",
    options: ["Escuela → Kiosco → Plaza", "Escuela → Club → Plaza", "Escuela → Plaza por la avenida", "Escuela → Club → Kiosco → Plaza"],
    correct: 0,
    notes: "Grafo con pesos: 5 contra 6, 7 y 6.",
  },
  {
    id: "B6",
    part: "B",
    practice: "algoritmo",
    facts: [
      "Un inspector recorre la fila de izquierda a derecha, mirando dos robots vecinos por vez.",
      "Si el de la izquierda tiene un número más grande, los hace cambiar de lugar.",
      "Después avanza un lugar y vuelve a mirar, hasta llegar al final. Recorre la fila una sola vez.",
    ],
    prompt: "¿Cómo queda la fila cuando el inspector termina?",
    figure: "fila",
    optionFigure: "fila",
    options: ["1, 3, 2, 4", "1, 2, 3, 4", "3, 1, 2, 4", "1, 3, 4, 2"],
    correct: 0,
    notes: "Una pasada de burbuja. El distractor 'todo ordenado' es el error típico.",
  },
  {
    id: "B7",
    part: "B",
    practice: "evaluar",
    facts: [
      "Hay una fila de 6 luces. Algunas están prendidas y otras apagadas.",
      "Cada luz tiene un botón que la cambia: si está prendida la apaga y si está apagada la prende.",
      "El robot recorre la fila pasando por cada luz.",
    ],
    prompt: "¿Qué instrucción apaga todas las luces, sin importar cuáles estaban prendidas?",
    figure: "luces",
    options: [
      "En cada luz: si está prendida, apretar el botón",
      "En cada luz: apretar el botón",
      "En la primera luz: apretar el botón 6 veces",
      "Pasar por todas las luces sin apretar nada",
    ],
    correct: 0,
    notes: "Evaluar qué instrucción generaliza a cualquier configuración inicial.",
  },
  {
    id: "B8",
    part: "B",
    practice: "logica",
    facts: ["La puerta se abre si el robot tiene la llave O si la luz está verde.", "Pero si el robot lleva una gema, la puerta NUNCA se abre."],
    prompt: "¿En cuál de estas situaciones se abre la puerta?",
    figure: "puerta",
    optionFigure: "puerta",
    options: [
      "Tiene la llave, la luz está roja y no lleva gema",
      "No tiene la llave, la luz está verde y lleva una gema",
      "No tiene la llave, la luz está roja y no lleva gema",
      "Tiene la llave, la luz está verde y lleva una gema",
    ],
    correct: 0,
    notes: "Combinación de O, Y y NO. Las opciones se dibujan: llave (tachada si no la tiene), semáforo y gema (tachada si no la lleva).",
  },
];
