// Parte A — "Programá al robot" (20 ítems). Ver docs/02-banco-de-items.md.
import {
  c,
  call,
  e,
  HOLE,
  ifHole,
  ifPath,
  ifRock,
  optCond,
  optDef,
  optPiece,
  optProg,
  path,
  prog,
  rep,
  rock,
  seq,
  until,
  whileP,
  type ItemA,
} from "./model";

const PROMPT_MAZE = "Llevá al robot hasta la base.";
const PROMPT_CANVAS = "El robot pinta mientras se mueve. ¿Qué programa dibuja esta figura?";

export const ITEMS_A: ItemA[] = [
  // ───────────────────────── A1 · Secuencias ─────────────────────────
  {
    id: "A1.1",
    part: "A",
    block: "A1",
    concept: "secuencias",
    task: "S",
    prompt: PROMPT_MAZE,
    map: {
      kind: "maze",
      cols: 4,
      rows: 4,
      start: c(1, 1),
      base: c(4, 3),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(3, 1), c(4, 1)),
        e(c(2, 1), c(2, 2)), e(c(4, 1), c(4, 2)),
        e(c(1, 2), c(2, 2)), e(c(2, 2), c(3, 2)),
        e(c(1, 2), c(1, 3)), e(c(3, 2), c(3, 3)), e(c(4, 2), c(4, 3)),
        e(c(1, 3), c(2, 3)), e(c(3, 3), c(4, 3)),
        e(c(2, 3), c(2, 4)), e(c(3, 3), c(3, 4)),
        e(c(1, 4), c(2, 4)), e(c(2, 4), c(3, 4)), e(c(3, 4), c(4, 4)),
      ],
    },
    options: [optProg(seq("→↓→↓→")), optProg(seq("→→↓↓→")), optProg(seq("↓→↓→→")), optProg(seq("→↓→↓↓"))],
    correct: 0,
    notes: "Ancla fácil. Distractores: mismas flechas en otro orden (chocan) y paso final equivocado.",
  },
  {
    id: "A1.2",
    part: "A",
    block: "A1",
    concept: "secuencias",
    task: "S",
    prompt: PROMPT_CANVAS,
    map: { kind: "canvas", cols: 4, rows: 3, start: c(1, 1), target: prog(seq("→→↓←↓→")) },
    options: [optProg(seq("→→↓←↓→")), optProg(seq("→→↓→↓←")), optProg(seq("→↓←↓→")), optProg(seq("→→↓←↓←"))],
    correct: 0,
    notes: "Distractores: figura espejada, primer tramo corto, último tramo al revés.",
  },

  // ───────────────────────── A2 · Repetir N veces ─────────────────────────
  {
    id: "A2.1",
    part: "A",
    block: "A2",
    concept: "repetir",
    task: "S",
    prompt: PROMPT_MAZE,
    map: {
      kind: "maze",
      cols: 6,
      rows: 3,
      start: c(1, 1),
      base: c(6, 3),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(3, 1)), e(c(3, 1), c(4, 1)),
        e(c(4, 1), c(4, 2)), e(c(4, 2), c(4, 3)),
        e(c(4, 3), c(5, 3)), e(c(5, 3), c(6, 3)),
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(1, 3)), e(c(1, 3), c(2, 3)),
      ],
    },
    options: [
      optProg([rep(3, seq("→")), rep(2, seq("↓")), rep(2, seq("→"))]),
      optProg([rep(2, seq("→")), rep(2, seq("↓")), rep(3, seq("→"))]),
      optProg([rep(3, seq("→")), rep(3, seq("↓")), rep(2, seq("→"))]),
      optProg([rep(3, seq("→")), rep(2, seq("↓")), rep(3, seq("→"))]),
    ],
    correct: 0,
    notes: "Distractores: contar mal en cada bucle (choca, se cae del mapa, se pasa de largo).",
  },
  {
    id: "A2.2",
    part: "A",
    block: "A2",
    concept: "repetir",
    task: "C",
    prompt: "Completá el programa para que el robot dibuje esta figura.",
    map: {
      kind: "canvas",
      cols: 5,
      rows: 6,
      start: c(1, 3),
      target: prog([rep(4, seq("→")), rep(2, seq("↓")), rep(4, seq("←"))]),
    },
    given: prog([rep(4, seq("→")), HOLE, rep(4, seq("←"))]),
    options: [optPiece([rep(2, seq("↓"))]), optPiece([rep(3, seq("↓"))]), optPiece([rep(2, seq("↑"))]), optPiece(seq("↓"))],
    correct: 0,
    notes: "Hay que contar el lado vertical (2) y elegir la dirección.",
  },
  {
    id: "A2.3",
    part: "A",
    block: "A2",
    concept: "repetir",
    task: "D",
    prompt: "Este programa hace que el robot se choque. ¿Cuál es el programa arreglado?",
    map: {
      kind: "maze",
      cols: 5,
      rows: 3,
      start: c(1, 1),
      base: c(5, 3),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(3, 1)), e(c(3, 1), c(4, 1)), e(c(4, 1), c(5, 1)),
        e(c(3, 1), c(3, 2)), e(c(3, 2), c(3, 3)),
        e(c(3, 3), c(4, 3)), e(c(4, 3), c(5, 3)),
        e(c(5, 1), c(5, 2)),
      ],
    },
    given: prog([rep(3, seq("→")), rep(2, seq("↓")), rep(2, seq("→"))]),
    givenNote: "Programa con error",
    options: [
      optProg([rep(2, seq("→")), rep(2, seq("↓")), rep(2, seq("→"))]),
      optProg([rep(3, seq("→")), rep(3, seq("↓")), rep(2, seq("→"))]),
      optProg([rep(3, seq("→")), rep(2, seq("↓")), ...seq("→")]),
      optProg([rep(3, seq("→")), rep(2, seq("↑")), rep(2, seq("→"))]),
    ],
    correct: 0,
    notes: "El robot queda en (4,1) y abajo hay pared: el error está en el primer bucle.",
  },

  // ───────────────────────── A3 · Repetir hasta / mientras ─────────────────────────
  {
    id: "A3.1",
    part: "A",
    block: "A3",
    concept: "hasta",
    task: "S",
    prompt: PROMPT_MAZE,
    map: {
      kind: "maze",
      cols: 4,
      rows: 4,
      start: c(1, 1),
      base: c(4, 4),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(2, 2)), e(c(2, 2), c(3, 2)),
        e(c(3, 2), c(3, 3)), e(c(3, 3), c(4, 3)), e(c(4, 3), c(4, 4)),
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(2, 2)), e(c(3, 1), c(4, 1)),
      ],
    },
    options: [
      optProg([until(seq("→↓"))]),
      optProg([until(seq("↓→"))]),
      optProg([rep(2, seq("→↓"))]),
      optProg([until(seq("→→↓"))]),
    ],
    correct: 0,
    notes: "Escalera de 3 escalones; el bucle contado se queda corto.",
  },
  {
    id: "A3.2",
    part: "A",
    block: "A3",
    concept: "hasta",
    task: "C",
    prompt: "Completá el programa para que el robot llegue a la base.",
    map: {
      kind: "maze",
      cols: 5,
      rows: 4,
      start: c(1, 1),
      base: c(4, 3),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(3, 1)), e(c(3, 1), c(4, 1)),
        e(c(4, 1), c(4, 2)), e(c(4, 2), c(4, 3)), e(c(4, 3), c(4, 4)),
      ],
    },
    given: prog([whileP("R", seq("→")), HOLE]),
    options: [optPiece([rep(2, seq("↓"))]), optPiece([whileP("D", seq("↓"))]), optPiece(seq("↓")), optPiece([rep(3, seq("↓"))])],
    correct: 0,
    notes: "El camino sigue una casilla más abajo de la base a propósito: 'mientras haya camino ↓' se pasa de largo.",
  },
  {
    id: "A3.3",
    part: "A",
    block: "A3",
    concept: "hasta",
    task: "D",
    prompt: "Este programa hace que el robot se choque. ¿Cuál es el programa arreglado?",
    map: {
      kind: "maze",
      cols: 5,
      rows: 3,
      start: c(1, 1),
      base: c(5, 3),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(3, 1)), e(c(3, 1), c(3, 2)),
        e(c(3, 2), c(4, 2)), e(c(4, 2), c(5, 2)), e(c(5, 2), c(5, 3)),
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(2, 2)),
      ],
    },
    given: prog([until(seq("→↓"))]),
    givenNote: "Programa con error",
    options: [
      optProg([until(seq("→→↓"))]),
      optProg([until(seq("→↑"))]),
      optProg([rep(2, seq("→↓"))]),
      optProg([until(seq("↓→"))]),
    ],
    correct: 0,
    notes: "Los escalones son de dos casillas: falta un → dentro del bucle.",
  },

  // ───────────────────────── A4 · Bucles anidados ─────────────────────────
  {
    id: "A4.1",
    part: "A",
    block: "A4",
    concept: "anidados",
    task: "S",
    prompt: PROMPT_CANVAS,
    map: { kind: "canvas", cols: 7, rows: 4, start: c(1, 4), target: prog([rep(3, [rep(2, seq("→")), ...seq("↑")])]) },
    options: [
      optProg([rep(3, [rep(2, seq("→")), ...seq("↑")])]),
      optProg([rep(2, [rep(3, seq("→")), ...seq("↑")])]),
      optProg([rep(3, seq("→↑"))]),
      optProg([rep(6, seq("→")), rep(3, seq("↑"))]),
    ],
    correct: 0,
    notes: "Escalera de 3 escalones de 2. Distractores: bucles intercambiados, sin anidar, secuencial.",
  },
  {
    id: "A4.2",
    part: "A",
    block: "A4",
    concept: "anidados",
    task: "C",
    prompt: "Completá el programa para que el robot llegue a la base.",
    map: {
      kind: "maze",
      cols: 5,
      rows: 3,
      start: c(1, 1),
      base: c(5, 1),
      paths: [
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(1, 3)),
        e(c(2, 1), c(2, 2)), e(c(2, 2), c(2, 3)),
        e(c(3, 1), c(3, 2)), e(c(3, 2), c(3, 3)),
        e(c(4, 1), c(4, 2)), e(c(4, 2), c(4, 3)),
        e(c(1, 3), c(2, 3)), e(c(2, 1), c(3, 1)), e(c(3, 3), c(4, 3)), e(c(4, 1), c(5, 1)),
        e(c(5, 1), c(5, 2)), e(c(5, 2), c(5, 3)),
      ],
    },
    given: prog([rep(2, [HOLE, ...seq("→"), rep(2, seq("↑")), ...seq("→")])]),
    options: [optPiece([rep(2, seq("↓"))]), optPiece([rep(2, seq("↑"))]), optPiece(seq("↓")), optPiece([rep(3, seq("↓"))])],
    correct: 0,
    notes: "Laberinto peine: bajar 2, derecha, subir 2, derecha; dos veces.",
  },
  {
    id: "A4.3",
    part: "A",
    block: "A4",
    concept: "anidados",
    task: "D",
    prompt: "Este programa dibuja otra figura. ¿Cuál es el programa arreglado?",
    map: { kind: "canvas", cols: 6, rows: 7, start: c(1, 7), target: prog([rep(3, [...seq("→"), rep(2, seq("↑"))])]) },
    given: prog([rep(3, [rep(2, seq("→")), ...seq("↑")])]),
    givenNote: "Programa con error",
    options: [
      optProg([rep(3, [...seq("→"), rep(2, seq("↑"))])]),
      optProg([rep(2, [rep(2, seq("→")), ...seq("↑")])]),
      optProg([rep(3, seq("→↑"))]),
      optProg([rep(3, [rep(2, seq("↑")), ...seq("→")])]),
    ],
    correct: 0,
    notes: "Los escalones son 1 a la derecha y 2 arriba: el bucle interno tiene que ser el de ↑.",
  },

  // ───────────────────────── A5 · Si (condicional simple) ─────────────────────────
  {
    id: "A5.1",
    part: "A",
    block: "A5",
    concept: "si",
    task: "S",
    prompt: "Llevá al robot hasta la base esquivando las rocas.",
    map: { kind: "maze", cols: 6, rows: 3, start: c(1, 1), base: c(6, 3), allPaths: true, rocks: [c(2, 1), c(4, 2)] },
    options: [
      optProg([until([ifRock("R", seq("↓")), ...seq("→")])]),
      optProg([until([...seq("→"), ifRock("R", seq("↓"))])]),
      optProg([until([ifRock("R", seq("↑")), ...seq("→")])]),
      optProg([until(seq("↓→"))]),
    ],
    correct: 0,
    notes: "Distractores: chequear después de moverse (choca), desvío hacia arriba (se cae), sin condicional.",
  },
  {
    id: "A5.2",
    part: "A",
    block: "A5",
    concept: "si",
    task: "C",
    prompt: "Completá la condición para que el robot llegue a la base.",
    map: {
      kind: "maze",
      cols: 6,
      rows: 3,
      start: c(1, 1),
      base: c(6, 3),
      allPaths: true,
      walls: [e(c(1, 2), c(2, 2))],
      rocks: [c(3, 1), c(5, 2)],
    },
    given: prog([until([ifHole(seq("↓")), ...seq("→")])]),
    options: [optCond(rock("R")), optCond(path("D")), optCond(rock("D")), optCond(rock("L"))],
    correct: 0,
    notes: "'hay camino ↓' baja en la primera casilla y choca con la pared; las otras chocan con la roca.",
  },
  {
    id: "A5.3",
    part: "A",
    block: "A5",
    concept: "si",
    task: "D",
    prompt: "Este programa hace que el robot se choque. ¿Cuál es el programa arreglado?",
    map: { kind: "maze", cols: 6, rows: 3, start: c(1, 2), base: c(6, 3), allPaths: true, rocks: [c(3, 2), c(5, 1)] },
    given: prog([until([ifRock("R", seq("↑")), ...seq("→")])]),
    givenNote: "Programa con error",
    options: [
      optProg([until([ifRock("R", seq("↓")), ...seq("→")])]),
      optProg([until([ifRock("U", seq("↑")), ...seq("→")])]),
      optProg([until([...seq("→"), ifRock("R", seq("↑"))])]),
      optProg([until([ifRock("R", seq("↓↓")), ...seq("→")])]),
    ],
    correct: 0,
    notes: "Esquivar por arriba lleva al robot a la fila 1, donde otra roca lo hace caer del mapa.",
  },

  // ───────────────────────── A6 · Si-sino ─────────────────────────
  {
    id: "A6.1",
    part: "A",
    block: "A6",
    concept: "si-sino",
    task: "S",
    prompt: PROMPT_MAZE,
    map: {
      kind: "maze",
      cols: 5,
      rows: 4,
      start: c(1, 1),
      base: c(5, 4),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(3, 1)), e(c(3, 1), c(3, 2)),
        e(c(3, 2), c(4, 2)), e(c(4, 2), c(4, 3)), e(c(4, 3), c(5, 3)), e(c(5, 3), c(5, 4)),
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(1, 3)),
      ],
    },
    options: [
      optProg([until([ifPath("R", seq("→"), seq("↓"))])]),
      optProg([until([ifPath("R", seq("→"), seq("↑"))])]),
      optProg([until([ifPath("D", seq("↓"), seq("→"))])]),
      optProg([until(seq("→↓"))]),
    ],
    correct: 0,
    notes: "Avanzar mientras se pueda; si no, bajar. La columna 1 es un callejón sin salida.",
  },
  {
    id: "A6.2",
    part: "A",
    block: "A6",
    concept: "si-sino",
    task: "C",
    prompt: "Completá la condición para que el robot llegue a la base.",
    map: { kind: "maze", cols: 6, rows: 3, start: c(1, 1), base: c(6, 3), allPaths: true, rocks: [c(3, 1), c(5, 2), c(2, 3)] },
    given: prog([until([ifHole(seq("↓"), seq("→"))])]),
    options: [optCond(rock("R")), optCond(rock("D")), optCond(path("D")), optCond(path("R"))],
    correct: 0,
    notes: "La roca de (2,3) hace fallar las condiciones sobre 'camino'.",
  },
  {
    id: "A6.3",
    part: "A",
    block: "A6",
    concept: "si-sino",
    task: "D",
    prompt: "Este programa hace que el robot se choque. ¿Cuál es el programa arreglado?",
    map: {
      kind: "maze",
      cols: 5,
      rows: 4,
      start: c(1, 1),
      base: c(5, 4),
      paths: [
        e(c(1, 1), c(2, 1)), e(c(2, 1), c(3, 1)), e(c(3, 1), c(3, 2)),
        e(c(3, 2), c(4, 2)), e(c(4, 2), c(4, 3)), e(c(4, 3), c(5, 3)), e(c(5, 3), c(5, 4)),
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(1, 3)),
      ],
    },
    given: prog([until([ifPath("R", seq("↓"), seq("→"))])]),
    givenNote: "Programa con error",
    options: [
      optProg([until([ifPath("R", seq("→"), seq("↓"))])]),
      optProg([until([ifPath("D", seq("↓"), seq("→"))])]),
      optProg([until([ifPath("R", seq("↓"), seq("↑"))])]),
      optProg([rep(8, [ifPath("R", seq("↓"), seq("→"))])]),
    ],
    correct: 0,
    notes: "Las ramas están invertidas. Un distractor entra en un bucle infinito (sube y baja).",
  },

  // ───────────────────────── A7 · Funciones simples ─────────────────────────
  {
    id: "A7.1",
    part: "A",
    block: "A7",
    concept: "funciones",
    task: "C",
    prompt: "Este programa usa la función Paso, pero falta su definición. ¿Cuál definición hace que dibuje esta figura?",
    map: {
      kind: "canvas",
      cols: 9,
      rows: 5,
      start: c(1, 5),
      target: prog([rep(3, [call("Paso")]), ...seq("→→")], [{ name: "Paso", body: seq("→↑") }]),
    },
    given: prog([rep(3, [call("Paso")]), ...seq("→→")]),
    options: [optDef("Paso", seq("→↑")), optDef("Paso", seq("↑→")), optDef("Paso", seq("→→↑")), optDef("Paso", seq("↑→→"))],
    correct: 0,
    notes: "Escalera de 3 escalones de 1 y una línea final de 2.",
  },
  {
    id: "A7.2",
    part: "A",
    block: "A7",
    concept: "funciones",
    task: "C",
    prompt: "Completá el programa para que el robot llegue a la base.",
    map: {
      kind: "maze",
      cols: 5,
      rows: 4,
      start: c(1, 1),
      base: c(4, 4),
      paths: [
        e(c(1, 1), c(1, 2)), e(c(1, 2), c(2, 2)), e(c(2, 2), c(3, 2)), e(c(3, 2), c(3, 3)),
        e(c(3, 3), c(3, 4)), e(c(3, 4), c(4, 4)),
        e(c(3, 2), c(4, 2)), e(c(4, 2), c(4, 3)), e(c(4, 3), c(5, 3)),
      ],
    },
    given: prog([call("Bajar"), HOLE, call("Bajar")], [{ name: "Bajar", body: seq("↓→") }]),
    options: [optPiece(seq("→↓")), optPiece(seq("↓→")), optPiece([call("Bajar")]), optPiece(seq("→→"))],
    correct: 0,
    notes: "Hay que ejecutar mentalmente la función dos veces y leer la pared entre (2,2) y (2,3).",
  },
  {
    id: "A7.3",
    part: "A",
    block: "A7",
    concept: "funciones",
    task: "E",
    prompt: "Este programa usa la función Cuadro y dibuja la figura. ¿Cuál de estos programas SIN función dibuja exactamente lo mismo?",
    map: {
      kind: "canvas",
      cols: 5,
      rows: 3,
      start: c(1, 1),
      target: prog([rep(2, [call("Cuadro"), ...seq("→")])], [{ name: "Cuadro", body: seq("→↓←↑") }]),
    },
    given: prog([rep(2, [call("Cuadro"), ...seq("→")])], [{ name: "Cuadro", body: seq("→↓←↑") }]),
    options: [
      optProg([rep(2, seq("→↓←↑→"))]),
      optProg(seq("→↓←↑→↓←↑")),
      optProg(seq("→↓←↑→→→↓←↑")),
      optProg(seq("→→↓←←↑")),
    ],
    correct: 0,
    notes: "El más difícil de la Parte A: hay que desenrollar función y bucle. Dos cuadrados pegados.",
  },
];
